extern const GeoLayout leg_sweeper_geo[];
extern Lights1 leg_sweeper_LegSweeperBody_lights;
extern Lights1 leg_sweeper_LegSweeperArms_lights;
extern u8 leg_sweeper_I4_OrnatePanel4_i8[];
extern u8 leg_sweeper_i4_Drillbit_i8[];
extern Vtx leg_sweeper_LegSweeperVisual_mesh_layer_1_vtx_cull[8];
extern Vtx leg_sweeper_LegSweeperVisual_mesh_layer_1_vtx_0[17];
extern Gfx leg_sweeper_LegSweeperVisual_mesh_layer_1_tri_0[];
extern Vtx leg_sweeper_LegSweeperVisual_mesh_layer_1_vtx_1[32];
extern Gfx leg_sweeper_LegSweeperVisual_mesh_layer_1_tri_1[];
extern Gfx mat_leg_sweeper_LegSweeperBody[];
extern Gfx mat_revert_leg_sweeper_LegSweeperBody[];
extern Gfx mat_leg_sweeper_LegSweeperArms[];
extern Gfx mat_revert_leg_sweeper_LegSweeperArms[];
extern Gfx leg_sweeper_LegSweeperVisual_mesh_layer_1[];
extern Gfx leg_sweeper_material_revert_render_settings[];
